###
POST http://localhost:8080/api/v1/edu_speciality/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE3MTY5MTA5NTksImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE3MTY5OTczNTksImlzcyI6InRlc3QifQ.oYyJlDZ0QGPJ9NHbpcCQwl3havSdCHendoVOqypUvRE

{
  "name": "Matimatika",
  "info": "matimatika yunalishi",
  "eduCenterId":  102
}

### !!!
GET localhost:8080/api/v1/edu_speciality/get-all

### !!!
GET localhost:8080/api/v1/edu_speciality/get-by-id/4

### !!!
GET localhost:8080/api/v1/edu_speciality/get-by-edu-center-id/3

### !!!
GET localhost:8080/api/v1/edu_speciality/get-by-name/PDP

### !!!
GET localhost:8080/api/v1/edu_speciality/get-by-info/Maktab

###
DELETE localhost:8080/api/v1/edu_speciality/delete-by-id/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE3MTY5MDk0OTEsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE3MTY5OTU4OTEsImlzcyI6InRlc3QifQ.mAqW0zyt3p8n6Luz2iN1UNI7JYk0CQ3I4v1wJ4aY8L0

### !!!
PUT localhost:8080/api/v1/edu_speciality/update-by-id/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE3MTY5MDk0OTEsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE3MTY5OTU4OTEsImlzcyI6InRlc3QifQ.mAqW0zyt3p8n6Luz2iN1UNI7JYk0CQ3I4v1wJ4aY8L0

{
  "name": "Humo",
  "info": "Yoq",
  "edu_center_id": 2
}