POST localhost:8080/users/register
Content-Type: application/json

{
  "firstName": "Hamidov",
  "lastName": "Humoyun",
  "phone": "1234",
  "password": "2222",
  "role": "USER"
}

###
POST localhost:8080/users/login
Content-Type: application/json

{
  "phone": "1234",
  "password": "2222"
}

###
GET localhost:8080/users/get-all
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE3MTY5MTA5NTksImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE3MTY5OTczNTksImlzcyI6InRlc3QifQ.oYyJlDZ0QGPJ9NHbpcCQwl3havSdCHendoVOqypUvRE
